networks:
  monitoring:
    external: true

volumes:
  snmp-agentx:


services:
  snmpd:
    build:
      context: ./snmp
      dockerfile: Dockerfile.snmpd
    container_name: bgpm-snmpd
    restart: unless-stopped
    networks: [ monitoring ]
    volumes:
      - ./snmp/agentx.cfg:/etc/snmp/snmpd.conf:ro
      - snmp-agentx:/var/agentx
    ports:
      - "1161:161/udp"  # expose SNMP to host for tests
    command: ["sh","-lc","exec snmpd -f -Lo -C -c /etc/snmp/snmpd.conf"]
    healthcheck:
      test: ["CMD-SHELL","snmpget -v2c -c public -r1 -t1 localhost 1.3.6.1.2.1.1.3.0 >/dev/null 2>&1"]
      interval: 5s
      timeout: 2s
      retries: 20

  snmp-agent:
    build:
      context: ./snmp
      dockerfile: Dockerfile.agent
    container_name: bgpm-snmp-agent
    restart: unless-stopped
    networks: [ monitoring ]
    environment:
      AGENTX_SOCKET: tcp:bgpm-snmpd:705
      BIRD_SOCK: /run/bird/bird.ctl
      ASN_DEFAULT: "65000"
    volumes:
      - bird-run:/run/bird:ro
      - snmp-agentx:/var/agentx       # <— match the same path
    depends_on:
      snmpd:
        condition: service_started
