x-logging-syslog: &logging
  driver: syslog
  options:
    syslog-address: "${SYSLOG_ADDRESS}"
    tag: "${SYSLOG_TAG:-bgpm}"
    syslog-format: "${SYSLOG_FORMAT:-rfc5424}"

volumes:
  bird-run: {}
  bgpmon-run: {}

services:
  bird:
    build: ./bird
    container_name: ${PROJECT_NAME:-bgpm}-bird
    restart: unless-stopped
    network_mode: host
    cap_add: [ NET_BIND_SERVICE ]
    env_file: [ .env ]
    environment:
      - LOCAL_AS=${LOCAL_AS}
      - ROUTER_ID=${ROUTER_ID}
      - PEER_COUNT=${PEER_COUNT}
      - BIRD_LOG_LEVEL=${BIRD_LOG_LEVEL:-info}
      - BIRD_GR_TIMER=${BIRD_GR_TIMER:-240}
      - BIRD_SCAN_TIME=${BIRD_SCAN_TIME:-15}
      - METRICS_INTERVAL=${METRICS_INTERVAL:-30}
    volumes:
      - ./bird/config:/etc/bird
      - bgpmon-run:/var/run/bgpmon
      - bird-run:/run/bird
    logging: *logging
    healthcheck:
      test: ["CMD-SHELL", "birdc -s /run/bird/bird.ctl show status | grep -q 'BIRD'"]
      interval: 30s
      timeout: 5s
      retries: 5

  syslog:
    profiles: ["local-syslog"]
    build: ./syslog-ng
    container_name: ${PROJECT_NAME:-bgpm}-syslog
    restart: unless-stopped
    ports:
      - "8514:8514/tcp"
      - "8514:8514/udp"
    volumes:
      - ./syslog-ng/data:/var/log/syslog

  # Legacy SNMP — disabled by default (kept for reference)
  snmpd_legacy:
    profiles: ["legacy-snmp"]
    image: alpine:3.20
    container_name: ${PROJECT_NAME:-bgpm}-snmpd-legacy
    restart: unless-stopped
    command: >
      sh -lc "apk add --no-cache net-snmp net-snmp-tools &&
              install -m 0755 /config/bgpmon_snmp.sh /usr/local/bin/bgpmon_snmp.sh &&
              exec /usr/sbin/snmpd -f -Le -C -c /config/snmpd.conf"
    cap_add: [ NET_BIND_SERVICE ]
    ports:
      - "161:161/udp"
    volumes:
      - ./snmp/snmpd.conf:/config/snmpd.conf:ro
      - ./snmp/bgpmon_snmp.sh:/config/bgpmon_snmp.sh:ro
      - bgpmon-run:/var/run/bgpmon:ro
